name: 'Hello Universe'
description: 'This action welcomes the user to the GitHub Universe'
inputs:
  GITHUB_TOKEN:
    description: 'This is the GitHub token that lets the action authenticate'
    required: true
  action:
    description: "Which action to run (e.g., test)"
    required: true
  framework:
    description: 'Availables:  react, react_native'
    required: true
  package_manager:
    description: 'Availables:  yarn, npm, pnpm'
    required: false
    default: "yarn"
  commands:
    description: 'List of commands: test, coverage, lint, prettier, build'
    required: false
    default: "test,coverage,lint,prettier,build"
outputs:
  OUTCOME:
    description: 'An example of outcome'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: 'yellow'
