name: Hello Universe 1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: YOUR_GITHUB_USER_NAME/YOUR_GITHUB_REPO_NAME@main
