name: Managing WorkFlow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wilsonmdrs/javascript-action@main
        name: Say Hello
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            action: "SAY_HELLO"
      - uses: wilsonmdrs/javascript-action@main
        name: Use Core
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            action: "USE_CORE"
            input_1: "Testing 1 2 3"
