name: Managing WorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: wilsonmdrs/javascript-action@main
        name: Run Pipeline test
        with:
          action: "test"
          framework: "react"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
