name: Managing WorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: wilsonmdrs/javascript-action@main
        name: Say Hello
        with:
          action: "SAY_HELLO"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: wilsonmdrs/javascript-action@main
        name: Use Core
        with:
          action: "USE_CORE"
          input_1: "Testing 1 2 3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
